run_python_run/repl/urls.py
from django.conf.urls import url

from .views import (
    ReplIndexView,
    ReplCodeRunView,
    ReplCodeRunResultView
)


urlpatterns = [
    url(regex='^$',
        view=ReplIndexView.as_view(),
        name='index'
    ),
    url(regex='^run/$',
        view=ReplCodeRunView.as_view(),
        name='code-run'
    ),
    url(regex='^code-run/(?P<code_run_id>[0-9]+)/$',
        view=ReplCodeRunResultView.as_view(),
        name='code-run-detail'
    )
]

run_python_run/run_python_run/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='repl:index')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^repl/', include('repl.urls', namespace='repl')),
    url(r'^admin/', admin.site.urls),
]

run_python_run/users/urls.py
from django.conf.urls import url

from .views import LoginView, RegisterView, LogoutView


urlpatterns = [
    url(regex='^login/$',
        view=LoginView.as_view(),
        name='login'
    ),
    url(regex='^register/$',
        view=RegisterView.as_view(),
        name='register'
    ),
    url(regex='^logout/$',
        view=LogoutView.as_view(),
        name='logout'
    )
]

run_python_run/repl/models.py
from django.db import models


class CodeRun(models.Model):
    run_id = models.PositiveIntegerField()
    run_status = models.CharField(max_length=255)
    output = models.TextField()

run_python_run/repl/forms.py
from django import forms


class CodeRunForm(forms.Form):
    code = forms.CharField(widget=forms.Textarea())

run_python_run/users/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

run_python_run/repl/views.py
from django.views.generic import View, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import redirect

from .forms import CodeRunForm
from .services import run_code
from .models import CodeRun


class ReplIndexView(LoginRequiredMixin, ListView):
    template_name = 'repl/index.html'
    queryset = CodeRun.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['code_run_form'] = CodeRunForm()

        return context


class ReplCodeRunResultView(LoginRequiredMixin, DetailView):
    model = CodeRun
    pk_url_kwarg = 'code_run_id'

    template_name = 'repl/code_run_detail.html'


class ReplCodeRunView(LoginRequiredMixin, View):
    def post(self, request):
        form = CodeRunForm(request.POST)

        if form.is_valid():
            code_run = run_code(**form.cleaned_data)

            return redirect('repl:code-run-detail', code_run_id=code_run.id)

        return redirect('repl:index')

run_python_run/users/views.py
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError

from django.shortcuts import redirect

from django.views.generic import View, FormView
from django.contrib.auth import views as auth_views

from .forms import RegisterForm
from .services import user_registration_flow


class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'

    def get_redirect_url(self):
        return reverse('repl:index')


class RegisterView(FormView):
    template_name = 'users/register.html'
    form_class = RegisterForm

    def form_valid(self, form):
        try:
            user_registration_flow(**form.cleaned_data)
        except ValidationError as error:
            for field, errors in error.error_dict.items():
                for error in errors:
                    form.add_error(field, error)

            return self.form_invalid(form)

        return redirect('users:login')


class LogoutView(auth_views.LogoutView):
    pass

run_python_run/templates/base.html
<html>
  <head>
    <title>Run Python Run</title>
    <style>
      pre {
        background-color: lightgrey;
      }
    </style>
  </head>
  <body>
  {% block content %}

  {% endblock content%}
  <hr /> 
  <footer>
    WiFi password: <strong>europython2017</strong>
  </footer>
  </body>
</html>

run_python_run/templates/repl/code_run_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Code run detail</h1>

  <p>Run id: {{ object.run_id }}</p>
  <p>Run status: {{ object.run_status }} </p>
  <p>Output:</p>

  <pre>{{ object.output }}</pre>
{% endblock content %}

run_python_run/templates/repl/index.html
{% extends "base.html" %}

{% block content %}
  <h1>REPL index</h1>

  <form method="POST" action="{% url 'repl:code-run' %}">
    <p>
      {{ code_run_form }}
      {% csrf_token %}
    </p>
    <button>Run Python!</button>
  </form>

  <hr />

  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Run id</th>
        <th>Run status</th>
        <th>Output</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for obj in object_list %}
        <tr>
          <td>{{ obj.id }}</td>
          <td>{{ obj.run_id }}</td>
          <td>{{ obj.run_status }}</td>
          <td><pre>{{ obj.output }}</pre></td>
          <td>
            <a href="{% url 'repl:code-run-detail' code_run_id=obj.id %}">View</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

run_python_run/templates/users/login.html
{% extends "base.html" %}

{% block content %}
  <h1>Login here</h1>

  <div>
    <form action="" method="POST">
      {{ form }}
      {% csrf_token %}
      <button>Login</button>
    </form>
  </div>

  <div>
    <a href="{% url 'users:register' %}">Or register</a>
  </div>
{% endblock %}

run_python_run/templates/users/register.html
{% extends "base.html" %}

{% block content %}
  <h1>Registration</h1>

  <div>
    <form action="" method="POST">
      {{ form }}
      {% csrf_token %}
      <button>Register</button>
    </form>
  </div>

  <div>
    <a href="{% url 'users:login' %}">Or login</a>
  </div>
{% endblock content %}